# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: Regression tests
run-name: Regression test for a pull request from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
jobs:
  Sim-VCS:
    runs-on: self-hosted        # runs on a server with Synopsys VCS installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Compile
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}
          action.sim
      - name: Sim-No-Dump
        run: ./simv
  Lint-Spyglass-RTL-Handoff:
    runs-on: self-hosted        # runs on a server with Synopsys Spyglass installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Spyglass-Lint
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}
          action.lint
      - name: Report (moresimple)
        run: cat reports/moresimple.rpt
      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: moresimple.rpt
          path: reports/moresimple.rpt
#  Design-Compiler-UMC28nm:
#    runs-on: self-hosted        # runs on a server with Synopsys Design Compiler installed
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#      - name: Synthesis
#        run: |
#          source ${{github.workspace}}/env.source ${{github.workspace}}
#          action.syn
  RDL-PeakRDL:
    runs-on: ubuntu-latest    # GitHub runner
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python3 -m pip install peakrdl
      - name: RTL generation
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}
          peakrdl regblock registers/systemRDL/AIDC_LITE.rdl -o regblock/ --cpuif apb3-flat
          
          #action.syn
