# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: RDL-PeakRDL
run-name: Generate HDL, UVM, C headers, documents from Register Description Language input from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
    paths:
      - registers/systemRDL/*
  workflow_dispatch:

jobs:
  RDL-PeakRDL:
    runs-on: ubuntu-latest    # GitHub runner
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python3 -m pip install peakrdl
      - name: RTL generation
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}
          peakrdl regblock registers/systemRDL/AIDC_LITE.rdl -o regblock/ --cpuif apb3-flat
      - name: Commit changes
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add regblock/
          git commit -m "Update RDL-generated files"
      - name: Push changes
        uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: true
            
