# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: Release-RTL
run-name: Build a RTL release package from ${{ github.actor }}
on:
  release:
    types: [created]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create archive
        run: |
          zip -r delivery.zip . -x ".git*" -x "actions/**" -x "registers/**"
      - name: Create release
        id: create_release
        uses: actions/create_release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}-${{ github.sha }}
          release_name: Release ${{ github.ref }}-${{ github.sha }}
          draft: false
          prerelease: false
      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ./delivery.zip
          asset_name: delivery.zip
          asset_content_type: application/zip
