# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: Synthesis (TSMC65nm)
run-name: IP-level synthesis (TSMC65nm) from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 5 * * *'    # 5:30 AM (UTC), any day of the month, any month, any day of the week
  workflow_dispatch:

jobs:
  Design-Compiler:
    # runs on a server with Synopsys Design Compiler installed
    runs-on: self-hosted        
    steps:
      # checkout the repository (with its submodules) to the runner
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      # run synthesis and generate report in ${SYN_OUT}
      - name: Synthesis
        uses: scalable-arch/rtl-actions/syn_TSMC65@590868988f691b7edfd8b9af88236c20fe637821
      # output report on github action consoles
      - name: Report (Design, Timing, Area, Power)
        uses: scalable-arch/rtl-actions/syn-report@590868988f691b7edfd8b9af88236c20fe637821
