# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: Synthesis (Synopsys 32/28nm Generic)
run-name: IP-level synthesis (SAED32_EDK) from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 5 * * *'    # 5:30 AM (UTC), any day of the month, any month, any day of the week
  workflow_dispatch:

jobs:
  Design-Compiler:
    runs-on: self-hosted        # runs on a server with Synopsys Design Compiler installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Synthesis
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}
          action.syn_SAED32
      - name: Report (Design)
        run: cat work.syn/*.design.rpt
      - name: Report (Timing)
        run: cat work.syn/*.timing.rpt
      - name: Report (Area)
        run: cat work.syn/*.area.rpt
      - name: Report (Power)
        run: cat work.syn/*.power.rpt
