# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: Synthesis VCS 
run-name: IP-level synthesis using VCS from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 5 * * *'    # 5:30 AM (UTC), any day of the month, any month, any day of the week
  workflow_dispatch:

# workflow executed in a action_runner (self-hosted)
# if you want to use another process or out directory, change the environment variables L.20-21
jobs:
  Design-Compiler:
    # runs on a server with Synopsys Design Compiler installed
    runs-on: self-hosted
    env:
      SYN_PROCESS: UMC28
      SYN_OUT_DIR: ${{github.workspace}}/work.syn
    steps:
      # checkout the repository (with its submodules) to the runner
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      # run synthesis and generate report in ${WORKING_DIR}/work.syn
      - name: Synthesis
        uses: scalable-arch/rtl-actions/syn_VCS@829b32998bb22f0f5a5c0cb9f212e4664073779e
        with:
          process: ${{env.SYN_PROCESS}}
          out: ${{env.SYN_OUT_DIR}}
      # cat output report on github action consoles
      - name: Report (Design)
        run: cat ${{env.SYN_OUT_DIR}}/*.design.rpt
      - name: Report (Timing)
        run: cat ${{env.SYN_OUT_DIR}}/*.timing.rpt
      - name: Report (Area)
        run: cat ${{env.SYN_OUT_DIR}}/*.area.rpt
      - name: Report (Power)
        run: cat ${{env.SYN_OUT_DIR}}/*.power.rpt
      # - name: Report (Design, Timing, Area, Power)
      #   uses: scalable-arch/rtl-actions/syn_report@829b32998bb22f0f5a5c0cb9f212e4664073779e
      #   with:
      #     out: ${{env.SYN_OUT_DIR}}